use_frameworks!
platform :ios, '8.0'
project 'LBTools.xcodeproj'
target 'LBTools_Example' do
  pod 'LBTools', :path => '../'

  target 'LBTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
